# azure-k8s-manifests.yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: pixelbloom-prod
---
# Secrets for database connection
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: pixelbloom-prod
type: Opaque
data:
  # echo -n "pixelbloom-postgres-1750202966.postgres.database.azure.com" | base64
  POSTGRES_HOST: cGl4ZWxibG9vbS1wb3N0Z3Jlcy0xNzUwMjAyOTY2LnBvc3RncmVzLmRhdGFiYXNlLmF6dXJlLmNvbQ==
  # echo -n "postgres" | base64
  POSTGRES_USER: cG9zdGdyZXM=
  # echo -n "YourSecurePassword123!" | base64
  POSTGRES_PASSWORD: WW91clNlY3VyZVBhc3N3b3JkMTIzIQ==
  # echo -n "inventory_db" | base64
  POSTGRES_DB: aW52ZW50b3J5X2Ri
  # echo -n "5432" | base64
  POSTGRES_PORT: NTQzMg==
---
# ConfigMap for application configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: pixelbloom-prod
data:
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  DEBUG: "false"
---
# Inventory Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: pixelbloom-prod
  labels:
    app: inventory-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8001"
    spec:
      containers:
      - name: inventory-service
        image: pixelbloomacr1750202956.azurecr.io/inventory-service:latest
        imagePullPolicy: Always
        env:
        # Database connection variables
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_HOST
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_DB
        - name: POSTGRES_PORT
          valueFrom:
            secretKeyRef:
              name: postgres-secret
              key: POSTGRES_PORT
        # Application configuration
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: ENVIRONMENT
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: LOG_LEVEL
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DEBUG
        ports:
        - containerPort: 8001
          name: http
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        # Add startup probe for better handling of slow starts
        startupProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 12
---
# Service for Inventory Service
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: pixelbloom-prod
spec:
  selector:
    app: inventory-service
  ports:
  - port: 80
    targetPort: 8001
    protocol: TCP
  type: ClusterIP
---
# Horizontal Pod Autoscaler
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: inventory-service-hpa
  namespace: pixelbloom-prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: inventory-service
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 4
        periodSeconds: 15
      selectPolicy: Max
---
# Load Balancer Service (optional - for external access)
apiVersion: v1
kind: Service
metadata:
  name: inventory-service-lb
  namespace: pixelbloom-prod
spec:
  selector:
    app: inventory-service
  ports:
  - port: 80
    targetPort: 8001
    protocol: TCP
  type: LoadBalancer