# azure-k8s-manifests.yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: pixelbloom-prod
---
apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: pixelbloom-prod
type: Opaque
data:
  POSTGRES_HOST: aW52ZW50b3J5LWRi          # base64 for "inventory-db"
  POSTGRES_USER: Z3Vlc3Q=                  # base64 for "guest"
  POSTGRES_PASSWORD: Z3Vlc3Q=              # base64 for "guest"
  POSTGRES_DB: aW52ZW50b3J5X2Ri            # base64 for "inventory_db"
  POSTGRES_PORT: NTQzMg==                  # base64 for "5432"
---
# ConfigMap for application configuration
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: pixelbloom-prod
data:
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  DEBUG: "false"
---
# PersistentVolumeClaims
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inventory-db-storage-pvc
  namespace: pixelbloom-prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: inventory-uploads-pvc
  namespace: pixelbloom-prod
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
# PostgreSQL Database Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-db
  namespace: pixelbloom-prod
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-db
  template:
    metadata:
      labels:
        app: inventory-db
    spec:
      containers:
      - name: postgres
        image: postgres:14
        env:
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          value: inventory_db
        - name: PGDATA
          value: /var/lib/postgresql/data/pgdata
        ports:
        - containerPort: 5432
        volumeMounts:
        - name: inventory-db-storage
          mountPath: /var/lib/postgresql/data
        readinessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - guest
          initialDelaySeconds: 10
          periodSeconds: 5
        livenessProbe:
          exec:
            command:
            - pg_isready
            - -U
            - guest
          initialDelaySeconds: 30
          periodSeconds: 10
        resources:
          requests:
            cpu: 100m
            memory: 256Mi
          limits:
            cpu: 500m
            memory: 512Mi
      volumes:
      - name: inventory-db-storage
        persistentVolumeClaim:
          claimName: inventory-db-storage-pvc
---
# PostgreSQL Service
apiVersion: v1
kind: Service
metadata:
  name: inventory-db
  namespace: pixelbloom-prod
spec:
  selector:
    app: inventory-db
  ports:
  - port: 5432
    targetPort: 5432
---
# Inventory Service Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-service
  namespace: pixelbloom-prod
  labels:
    app: inventory-service
spec:
  replicas: 2
  selector:
    matchLabels:
      app: inventory-service
  template:
    metadata:
      labels:
        app: inventory-service
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: "/metrics"
        prometheus.io/port: "8001"
    spec:
      containers:
      - name: inventory-service
        image: pixelbloomacr1750202956.azurecr.io/inventory-service:latest
        imagePullPolicy: Always
        env:
        # Database connection variables
        - name: POSTGRES_HOST
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_HOST
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_USER
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_PASSWORD
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_DB
        - name: POSTGRES_PORT
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_PORT
        # Application configuration
        - name: ENVIRONMENT
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: ENVIRONMENT
        - name: LOG_LEVEL
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: LOG_LEVEL
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              name: app-config
              key: DEBUG
        ports:
        - containerPort: 8001
          name: http
        resources:
          requests:
            cpu: 100m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi
        readinessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 15
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
        livenessProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 30
          periodSeconds: 15
          timeoutSeconds: 5
          failureThreshold: 3
        # Add startup probe for better handling of slow starts
        startupProbe:
          httpGet:
            path: /health
            port: 8001
          initialDelaySeconds: 10
          periodSeconds: 5
          timeoutSeconds: 5
          failureThreshold: 12
---
# Service for Inventory Service
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
  namespace: pixelbloom-prod
spec:
  selector:
    app: inventory-service
  ports:
  - port: 8001
    targetPort: 8001
    protocol: TCP
  type: LoadBalancer
---
# Horizontal Pod Autoscaler
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: inventory-service-hpa
  namespace: pixelbloom-prod
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: inventory-service
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80
  behavior:
    scaleDown:
      stabilizationWindowSeconds: 300
      policies:
      - type: Percent
        value: 50
        periodSeconds: 60
    scaleUp:
      stabilizationWindowSeconds: 0
      policies:
      - type: Percent
        value: 100
        periodSeconds: 15
      - type: Pods
        value: 4
        periodSeconds: 15
      selectPolicy: Max
---
# Load Balancer Service (optional - for external access)
apiVersion: v1
kind: Service
metadata:
  name: inventory-service-lb
  namespace: pixelbloom-prod
spec:
  selector:
    app: inventory-service
  ports:
  - port: 80
    targetPort: 8001
    protocol: TCP
  type: LoadBalancer