name: Debug and Scan

on:
  push:
    branches: [ main ]

jobs:
  scan:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Start and Debug App
        run: |
          echo "DATABASE_URL=${{ secrets.INVENTORY_DATABASE_URL }}" > .env.docker
          echo "RABBITMQ_HOST=rabbitmq" >> .env.docker
          
          echo "🚀 Starting containers..."
          docker compose up -d --build
          sleep 30
          
          echo "📊 Container status:"
          docker compose ps
          
          echo "📋 Full logs:"
          docker compose logs
          
          echo "🔍 What's listening on ports:"
          docker compose exec -T app netstat -tlnp 2>/dev/null || echo "netstat failed"
          
          echo "🌐 Port mapping check:"
          docker port $(docker compose ps -q app) 2>/dev/null || echo "No port mapping found"
          
          echo "🔌 Testing connectivity:"
          for port in 8000 8001 3000 5000 80; do
            echo "Testing port $port..."
            curl -I http://localhost:$port 2>/dev/null && echo "✅ Port $port works!" || echo "❌ Port $port failed"
          done
          
          echo "🐳 Container inspect:"
          docker compose exec -T app ps aux 2>/dev/null || echo "ps failed"

      - name: Run ZAP (only if app responds)
        run: |
          # Find which port actually works
          APP_PORT=""
          for port in 8000 8001 3000 5000 80; do
            if curl -f http://localhost:$port 2>/dev/null; then
              APP_PORT=$port
              echo "✅ Found working port: $port"
              break
            fi
          done
          
          if [ -n "$APP_PORT" ]; then
            echo "🔍 Running ZAP scan on port $APP_PORT"
            docker run --rm --network host \
              -v $(pwd):/zap/wrk/:rw \
              ghcr.io/zaproxy/zaproxy:stable \
              zap-baseline.py \
                -t http://localhost:$APP_PORT \
                -J zap-report.json \
                -I || echo "ZAP completed with warnings"
          else
            echo "❌ No working port found - skipping ZAP scan"
            echo "Check the logs above to see why your app isn't starting"
            exit 1
          fi

      - name: Upload Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: zap-report
          path: zap-report.json

      - name: Cleanup
        if: always()
        run: docker compose down