name: Build and Scan with OWASP ZAP

on:
  push:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest
    services:
      app:
        image: your-image-name:latest
        build:
          context: .
        ports:
          - 8001:8001  # your app port
        options: >-
          --health-cmd="curl --fail http://localhost:8001/health || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build OWASP ZAP container
        run: |
          docker pull owasp/zap2docker-stable

      - name: Wait for App to be ready
        run: |
          echo "Waiting for app container to be healthy..."
          for i in {1..20}; do
            curl -s http://localhost:8001/health && break
            sleep 5
          done

      - name: Run ZAP Scan
        run: |
          docker run --rm \
            --network host \
            owasp/zap2docker-stable zap-baseline.py \
            -t http://localhost:8001 \
            -g gen.conf -r zap_report.html

      - name: Upload ZAP report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap_report.html
