name: Minimal Security Test

on:
  push:
    branches: [ main ]

jobs:
  test-zap:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      
      # Start a simple test server first
      - name: Start Test Server
        run: |
          # Start a simple Python web server for testing
          python3 -m http.server 8001 &
          sleep 5
          curl -I http://localhost:8001 || echo "Test server failed"

      # Test ZAP on the simple server
      - name: Test ZAP Scan
        run: |
          docker run --rm \
            --network host \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py \
              -t http://localhost:8001 \
              -J test-report.json || echo "ZAP test completed"

      - name: Upload Test Report
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: zap-test-report
          path: test-report.json