name: Build and Scan with OWASP ZAP

on:
  push:
    branches:
      - main

jobs:
  zap_scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build FastAPI App Docker Image
        run: |
          docker build -t pixelbloom-app .

      - name: Create Docker network
        run: |
          docker network create zap-net

      - name: Run FastAPI App container
        run: |
          docker run -d --rm \
            --name pixelbloom-app \
            --network zap-net \
            -p 8001:8001 \
            pixelbloom-app

      - name: Wait for App to Become Healthy
        run: |
          echo "Waiting for app to become healthy..."
          for i in {1..20}; do
            if curl -s http://localhost:8001/health; then
              echo "App is up!"
              break
            fi
            sleep 5
          done

      - name: Create writable folder for ZAP output
        run: mkdir -p zap-output

      - name: Run OWASP ZAP Scan
        run: |
          docker run --rm \
            --network zap-net \
            -v $(pwd)/zap-output:/zap/wrk:rw \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py \
            -t http://pixelbloom-app:8001 \
            -g gen.conf \
            -r zap_report.html

      - name: Upload ZAP Report
        uses: actions/upload-artifact@v4
        with:
          name: zap-report
          path: zap-output/zap_report.html
