name: Security Scan

on:
  push:
    branches: [ main ]

jobs:
  scan:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Start Your App
        run: |
          echo "DATABASE_URL=${{ secrets.INVENTORY_DATABASE_URL }}" > .env.docker
          echo "RABBITMQ_HOST=rabbitmq" >> .env.docker
          docker compose up -d --build
          sleep 30

      - name: What's Actually Running?
        run: |
          echo "=== Containers ==="
          docker ps
          echo "=== Logs ==="
          docker compose logs
          echo "=== Network Test ==="
          curl -v http://localhost:8001 || echo "Nothing on 8001"
          echo "=== Port Check ==="
          ss -tlnp | grep :8001 || echo "No port 8001"

      - name: ZAP Scan
        run: |
          docker run --rm --network host \
            ghcr.io/zaproxy/zaproxy:stable \
            zap-baseline.py -t http://localhost:8001 -I || echo "ZAP done"

      - name: Cleanup
        if: always()
        run: docker compose down